kind: Pod
apiVersion: v1
metadata:
  name: env 
spec:
  containers:
    - name: nginx
      image: nginx
      resources:
        # Soft limits
        requests:
          memory: "68mi"
          cpu: "100m"
        # Hard limits
        limits:
          memory: "128mi"
          cpu: "150m"

