apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  # labels for Deployment resource
  labels:  # Pod Selectors we given here same it is paste in the Loadbalancer as well
    app: nginx
    tier: frontend
    purpose: deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
        tier : frontend
        purpose : deployment
    spec:
      containers:
        - name: nginx
          image: rahul8096/deployment:1.0
          ports:
            - containerPort: 80
---
# Load Balancer

kind : Service
apiVersion : v1
metadata : 
  name : nginx
spec :
  type : LoadBalancer
  selector : # here Selector acts as Service
    app: nginx
    tier: frontend
    purpose: deployment
  ports :
  - protocol : TCP
    port : 80 
    targetPort : 80
    nodePort : 30007
